# NoteBook to do the Data Analysis

In [ ]:
# Basics of python programming
print("Hello, World!")
# This is a simple Python script that prints a greeting message.
# You can expand this script to include more complex functionality as needed.


In [12]:
# Data types in Python
# Integer
x = 10
# Float
y = 10.5
# String
name = "Alice"
# Boolean
is_student = True
# List
fruits = ["apple", "banana", "cherry"]
# Dictionary
person = {"name": "Bob", "age": 25}
# Tuple
coordinates = (10.0, 20.0)
# Set
unique_numbers = {1, 2, 3, 4, 5}
# --- IGNORE ---


In [1]:
# Liberary of numpy
import numpy as np

In [ ]:
# Numpy array
# 1D array

arr = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", arr)

Numpy Array: [1 2 3 4 5]


In [3]:
# Numpy array 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Numpy Array:\n", arr_2d)


2D Numpy Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Numpy array 3D
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Numpy Array:\n", arr_3d)

3D Numpy Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Numpy Advanced Operations
# Array reshaping
reshaped_arr = arr_2d.reshape(3, 2)
print("Reshaped Array:\n", reshaped_arr)
# Array concatenation
concatenated_arr = np.concatenate((arr, arr))
print("Concatenated Array:", concatenated_arr)
# Array slicing
sliced_arr = arr_2d[:, 1]
print("Sliced Array:", sliced_arr)


Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Concatenated Array: [1 2 3 4 5 1 2 3 4 5]
Sliced Array: [2 5]
